[package]
name = "cli-for-anilist"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
serde_json = "1.0.148"
serde = { version = "1.0.228", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["json"] }
rpassword = "7.4.0"
ratatui = "0.29"
crossterm = "0.28"
open = "5.0"
axum = "0.7"
tower = "0.4"
tower-http = "0.5"
dotenv = "0.15"
urlencoding = "2.1"
